
  CREATE TABLE "PAXHC"."HC_METRICA_COL"
   (	"METRICA_COL_ID" NUMBER DEFAULT "PAXHC"."ISEQ$$_128416".nextval NOT NULL EN
ABLE,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"NOME" VARCHAR2(200 CHAR) NOT NULL ENABLE,
	 CONSTRAINT "METRICA_COL_PK" PRIMARY KEY ("METRICA_COL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"  ENABLE,
	 CONSTRAINT "METRICA_COL_FK_METRICA" FOREIGN KEY ("METRICA_ID")
	  REFERENCES "PAXHC"."HC_METRICA" ("METRICA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"

