
  CREATE TABLE "PAXHC"."HC_REL_ATTRXVERSAO"
   (	"REL_ATTR_ID" NUMBER NOT NULL ENABLE,
	"TIPO_REL_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "HC_REL_ATTRXVERSAO_PK" PRIMARY KEY ("REL_ATTR_ID", "TIPO_REL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"  ENABLE,
	 CONSTRAINT "REL_ATTRXVER_FK_REL_ATTR" FOREIGN KEY ("REL_ATTR_ID")
	  REFERENCES "PAXHC"."HC_REL_ATTR" ("REL_ATTR_ID") ENABLE,
	 CONSTRAINT "REL_ATTRXVER_FK_TIPO_REL" FOREIGN KEY ("TIPO_REL_ID")
	  REFERENCES "PAXHC"."HC_TIPO_REL" ("TIPO_REL_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"

