
  CREATE TABLE "PAXHC"."SCRIPT_METRICA"
   (	"SCRIPT_METRICA_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE
 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCY
CLE  NOT NULL ENABLE,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"SO" VARCHAR2(50),
	"VENDOR" VARCHAR2(50),
	"VERSAO" VARCHAR2(50),
	"COMANDO" VARCHAR2(4000) NOT NULL ENABLE,
	 PRIMARY KEY ("SCRIPT_METRICA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"  ENABLE,
	 CONSTRAINT "SCRIPT_METRICA_FK_METRICA" FOREIGN KEY ("METRICA_ID")
	  REFERENCES "PAXHC"."HC_METRICA" ("METRICA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_HC"

